name: CI

on: [push]
jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        nim-channel: [stable, devel]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-channel }}
    - name: Installation
      run: |
        nimble install -d -y
    - name: Test
      shell: bash
      run: |
        nim --version
        nimble test
    - name: Test with chronos
      shell: bash
      run: |
        nimble test -d:ChronosAsync
    - name: Chronos strict exception check
      run: |
        nimble c asyncthreadpool.nim --threads:on -d:ChronosAsync -d:chronosStrictException