name: CI

on: [push]
jobs:
  Test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        nim-channel: [stable, devel]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      shell: bash
      run: |
        export CHOOSENIM_NO_ANALYTICS=1
        curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
        export PATH=$HOME/.nimble/bin:$PATH
        choosenim ${{ matrix.nim-channel }}

    - name: Test
      shell: bash
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nim --version
        nimble test
